export default [
  'Dr. Aibek uulu Nursultan',
  'Dr. Asel kyzy Aigerim',
  'Dr. Erkin uulu Bakyt',
  'Dr. Meerim kyzy Gulzat',
  'Dr. Tilek uulu Almaz',
  'Dr. Aizada kyzy Nazira',
  'Dr. Kanat uulu Ruslan',
  'Dr. Anara kyzy Zhyldyz',
  'Dr. Kubanychbek uulu Ermek',
  'Dr. Cholpon kyzy Saltanat',
  'Dr. Zhyrgal uulu Talant',
  'Dr. Nurkyz kyzy Aisuluu',
  'Dr. Damir uulu Nurlan',
  'Dr. Elmira kyzy Ainura',
  'Dr. Azamat uulu Timurlan',
  'Dr. Nazgul kyzy Begimai',
  'Dr. Marat uulu Emil',
  'Dr. Kanykey kyzy Aygerim',
  'Dr. Bakytbek uulu Taalay',
  'Dr. Akmaral kyzy Ayzada',
]
