export default [
  'General Medicine',
  'Cardiology',
  'Neurology',
  'Dermatology',
  'Ophthalmology',
  'Pediatrics',
  'Orthopedics',
  'Endocrinology',
  'Psychiatry',
  'Physiotherapy',
  'Occupational Therapy',
  'Speech Therapy',
  'Gynecology',
  'Oncology',
  'Rheumatology',
]
